 - name: creat temp directory
   win_file:
      path: C:\Temp
      state: directory

 - name: Download the Apache installer
   win_get_url:
     url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.20/bin/apache-tomcat-8.0.20-windows-x64.zip
     dest: C:\Temp\apache-tomcat-8.0.20-windows-x64.zip

 - name: Unzip the tomcat Zip file
   win_unzip:
     src: C:\Temp\apache-tomcat-8.0.20-windows-x64.zip
     dest: C:\Apache-Tomcat
     delete_archive: yes

 - name: change path to bin
   win_command: cd C:\Apache-Tomcat\apache-tomcat-8.0.20\bin
   args:
     chdir: C:\Apache-Tomcat\apache-tomcat-8.0.20\bin
     creates: C:\Apache-Tomcat
